# Generated by Django 5.2.13 on 2026-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_legacy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('frozen', 'Muzlatilgan'), ('archived', 'Arxivlangan')], default='active', max_length=20),
        ),
    ]
