# Generated by Django 5.2.14 on 2026-06-03 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='companies.company')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_type', models.CharField(choices=[('monthly', 'Monthly'), ('per_lesson', 'Per Lesson'), ('upfront', 'Upfront')], default='monthly', max_length=20)),
                ('absent_policy', models.CharField(choices=[('ignore', 'Ignore'), ('deduct', 'Deduct from Debt'), ('penalty', 'Add Penalty')], default='ignore', max_length=20)),
                ('teacher_contract_break_policy', models.CharField(choices=[('full', 'Full Salary'), ('prorate', 'Prorated Salary'), ('none', 'No Salary')], default='full', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'db_table': 'company_settings',
            },
        ),
    ]
