# Generated by Django 5.2.14 on 2026-06-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='archive_billing_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('per_lesson', 'Per Lesson'), ('per_day', 'Per Day')], default='manual', max_length=20),
        ),
    ]
