# Generated by Django 5.2.13 on 2026-05-03 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_type', models.CharField(choices=[('monthly', 'Monthly'), ('per_lesson', 'Per Lesson'), ('upfront', 'Upfront')], default='monthly', max_length=20)),
                ('absent_policy', models.CharField(choices=[('ignore', 'Ignore'), ('deduct', 'Deduct from Debt'), ('penalty', 'Add Penalty')], default='ignore', max_length=20)),
                ('teacher_contract_break_policy', models.CharField(choices=[('full', 'Full Salary'), ('prorate', 'Prorated Salary'), ('none', 'No Salary')], default='full', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'db_table': 'company_settings',
            },
        ),
    ]
