# Generated by Django 5.2.14 on 2026-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companysettings_archive_billing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='teacher_contract_break_policy',
            field=models.CharField(choices=[('full', 'Full month'), ('per_lesson', 'Per Lesson'), ('per_day', 'Per Day'), ('manual', 'Manual')], default='full', max_length=20),
        ),
    ]
