# Generated by Django 5.2.14 on 2026-06-03 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('second_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, choices=[('banner', 'Banner'), ('friend', 'Friend'), ('parent', 'Parent'), ('social_media', 'Social Media'), ('other', 'Other')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('archived', 'Archived'), ('frozen', 'Frozen')], default='active', max_length=20)),
                ('archive_reason', models.CharField(blank=True, choices=[('graduated', 'Kursni bitirdi'), ('dropped_out', 'Tashlab ketdi')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='companies.company')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='leads.lead')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
