# Generated by Django 5.2.14 on 2026-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
