# Generated by Django 5.2.14 on 2026-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_chat_id_second',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
