# Generated by Django 5.2.13 on 2026-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('trial', 'Trial'), ('archived', 'Archived'), ('frozen', 'Frozen'), ('ignored', 'Ignored')], default='pending', max_length=20),
        ),
    ]
