# Generated by Django 5.2.13 on 2026-05-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_teachers_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
