# Generated by Django 5.2.13 on 2026-05-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_make_student_phone_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.student',),
        ),
    ]
