# Generated by Django 5.2.14 on 2026-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('frozen', 'Frozen'), ('left', 'Left')], default='trial', max_length=20),
        ),
    ]
