# Generated by Django 5.2.14 on 2026-06-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupstudent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='archive_billing_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
