# Generated by Django 5.2.13 on 2026-05-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_add_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='room',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
