# Generated by Django 5.2.13 on 2026-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('frozen', 'Frozen')], default='active', max_length=20),
        ),
    ]
