# Generated by Django 5.2.13 on 2026-05-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('a', 'Male'), ('b', 'Female'), ('c', 'Mixed')], max_length=1, null=True),
        ),
    ]
