# Generated by Django 5.2.13 on 2026-05-02 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20)),
                ('billing_type', models.CharField(choices=[('per_student', 'Per Student'), ('flat', 'Flat')], max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('students_count', models.IntegerField(blank=True, null=True)),
                ('amount_billed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('started_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
