# Generated by Django 5.2.14 on 2026-06-03 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent', models.PositiveIntegerField()),
                ('months', models.PositiveIntegerField()),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='companies.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='courses.course')),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
    ]
