from django.urls import path, include
from apps.students.views import ArchiveStudentsView

urlpatterns = [
    path('companies/', include('apps.companies.urls')),
    path('users/', include('apps.users.api_urls')),
    path('teachers/', include('apps.teachers.urls')),
    path('students/', include('apps.students.urls')),
    path('groups/', include('apps.groups.urls')),
    path('courses/', include('apps.courses.urls')),
    path('lessons/', include('apps.lessons.urls')),
    path('payments/', include('apps.payments.urls')),
    path('debts/', include('apps.debts.urls')),
    path('refunds/', include('apps.refunds.urls')),
    path('discounts/', include('apps.discounts.urls')),
    path('sms-templates/', include('apps.notifications.sms_urls')),
    path('awards/', include('apps.awards.urls')),
    path('expenses/', include('apps.expenses.urls')),
    path('', include('apps.staff.urls')),
    path('teacher-salaries/', include('apps.salaries.teacher_urls')),
    path('audit-logs/', include('apps.audit.urls')),
    path('notifications/', include('apps.notifications.urls')),
    path('announcements/', include('apps.notifications.announcement_urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('dashboard/', include('apps.companies.dashboard_urls')),
    path('profit-loss/', include('apps.expenses.pl_urls')),
    path('company-settings/', include('apps.companies.settings_urls')),
    path('staff-kpi-rules/', include('apps.salaries.kpi_urls')),
    path('grades/', include('apps.grades.urls')),
    path('student-notes/', include('apps.notes.urls')),
    path('leads/', include('apps.leads.urls')),
    path('attendance/', include('apps.attendance.urls')),
    path('rooms/', include('apps.rooms.urls')),
    path('', include('apps.sms.urls')),
    path('archive/students/', ArchiveStudentsView.as_view(), name='archive-students'),
]
