# Generated by Django 5.2.14 on 2026-06-22 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0007_add_freeze_billing_type'),
        ('debts', '0007_add_billing_month'),
        ('groups', '0004_groupstudent_archive_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('earned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='companies.company')),
                ('debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='debts.debt')),
                ('group_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='groups.groupstudent')),
            ],
            options={
                'db_table': 'refunds',
            },
        ),
    ]
