# Generated by Django 5.2.13 on 2026-05-02 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('lessons', '0002_initial'),
        ('salaries', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salaries', to='companies.company'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='teacherworklog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_work_logs', to='companies.company'),
        ),
        migrations.AddField(
            model_name='teacherworklog',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='teacherworklog',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersalary',
            unique_together={('teacher', 'month')},
        ),
    ]
