# Generated by Django 5.2.13 on 2026-05-03 09:55
# Duplicate of 0003_staffkpirule_staffsalary_kpi_amount; uses IF NOT EXISTS to be idempotent.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companysettings'),
        ('salaries', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE staff_salaries
                    ADD COLUMN IF NOT EXISTS kpi_amount numeric(15, 2) NOT NULL DEFAULT 0;

                CREATE TABLE IF NOT EXISTS staff_kpi_rules (
                    id          uuid         NOT NULL PRIMARY KEY,
                    name        varchar(255) NOT NULL,
                    role        varchar(20)  NOT NULL,
                    metric      varchar(30)  NOT NULL,
                    threshold   numeric(15, 2) NOT NULL,
                    bonus_amount numeric(15, 2) NOT NULL,
                    status      varchar(20)  NOT NULL DEFAULT 'active',
                    archived_at timestamptz  NULL,
                    created_at  timestamptz  NOT NULL,
                    company_id  uuid         NOT NULL
                        REFERENCES companies(id) ON DELETE CASCADE
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
