# Generated by Django 5.2.14 on 2026-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='archive_billing_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
