# Generated by Django 5.2.13 on 2026-05-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0003_staffkpirule_staffsalary_kpi_amount'),
        ('salaries', '0003_staffsalary_kpi_amount_staffkpirule'),
    ]

    operations = [
    ]
