# Generated by Django 5.2.14 on 2026-06-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0003_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='manual_amount_set',
            field=models.BooleanField(default=False),
        ),
    ]
