# Generated by Django 5.2.13 on 2026-05-02 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent'), ('per_student', 'Per Student')], max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salary_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('per_student_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kpi_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('hired_at', models.DateField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='companies.company')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
