# Generated by Django 5.2.13 on 2026-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_remove_role_from_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
