# Generated by Django 5.2.13 on 2026-05-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_status_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
    ]
