# Generated by Django 5.2.14 on 2026-06-03 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='discounts.discount'),
        ),
    ]
