# Generated by Django 5.2.13 on 2026-05-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('discounts', '0002_rebuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='discounts.discount'),
        ),
        migrations.AddField(
            model_name='debt',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
