# Generated by Django 5.2.14 on 2026-06-03 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0002_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='group_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='groups.groupstudent'),
        ),
    ]
