# Generated by Django 5.2.14 on 2026-06-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
