# Generated by Django 5.2.14 on 2026-06-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_debt_confirmed_at'),
        ('groups', '0004_groupstudent_archive_billing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='groups.groupstudent'),
        ),
    ]
