# Generated by Django 5.2.14 on 2026-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_debt_group_student_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='billing_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
