# Generated by Django 5.2.14 on 2026-06-03 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utility', 'Utility'), ('tax', 'Tax'), ('fine', 'Fine'), ('discount', 'Discount'), ('teacher_salary', 'Teacher Salary'), ('staff_salary', 'Staff Salary'), ('other', 'Other')], max_length=20)),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, default='')),
                ('expense_date', models.DateField()),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.company')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
    ]
