# Generated by Django 5.2.13 on 2026-05-23 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
                ('gender_type', models.CharField(blank=True, choices=[('a', 'Bolalar'), ('b', 'Qizlar'), ('c', 'Aralash')], max_length=1, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='companies.company')),
            ],
            options={
                'db_table': 'rooms',
                'unique_together': {('company', 'name')},
            },
        ),
    ]
