# Generated by Django 5.2.14 on 2026-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='type',
            field=models.CharField(choices=[('student', "O'quvchi"), ('parent', 'Ota-ona'), ('both', 'Ikkalasi')], default='student', max_length=10),
        ),
    ]
