# Generated by Django 5.2.14 on 2026-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('call', 'Call'), ('telegram', 'Telegram')], max_length=10),
        ),
    ]
